---
title: "New York Times 2020 Global Playlist"
subtitle: "Press *o* for *overview*"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, lucy, lucy-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}

options(htmltools.dir.version = FALSE)

xaringanExtra::use_tile_view()

xaringanExtra::use_share_again()

xaringanExtra::use_animate_css()

```


```{r, echo=FALSE}

library(readxl)

playlist <- read_excel("NewYorkTimes2020GlobalPlaylist.xlsx")

save(playlist, file = "playlist.RData")

```

# Songs

```{r, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}

library(countrycode)

library(plotly)

library(tidyr)

playlist_longer <- playlist %>% 
  pivot_longer(4:6) %>%
  select(song, group, name, value) %>%
  filter(!is.na(value))

playlist_longer$value[playlist_longer$value == "England"] <- "UK"

playlist_longer$country_iso <- countrycode(playlist_longer$value, 
                                 'country.name', 
                                 'iso3c')

g <- list(showframe = TRUE, 
          showcoastlines = TRUE, 
          showcountries = TRUE,
          showland = TRUE,
          projection = list(type = 'orthographic',
                            rotation = list(lon = 0,
                                            lat = 0,
                                            roll = 0)),
          showland = TRUE,
          showocean = TRUE,
          bgcolor = "black",
          landcolor = toRGB("white"))

plot_geo(playlist_longer,
         locations = ~country_iso,
         text = ~paste(song,
                       "\n", 
                       group, 
                       "\n", 
                       value),
         hoverinfo = 'text',
         marker = list(size=10, color = "green")) %>%
  layout(geo = g,
         paper_bgcolor='#000000',
         plot_bgcolor='#000000')

```


```{r, echo=FALSE, results='asis'}

for (i in 1:10){
  
  cat(paste0("---\n", # new slide
             "class: animated slideInRight \n",
             "# ", # header,
             i, 
             ": ",
             playlist$song[i],
             "\n",
             "### by ",
             playlist$group[i],
             "\n",
             playlist$EmbedCode[i],
             "\n"))
  
}

```





